name: Publish Package to NPM

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21
      - name: Install NPM Dependencies
        run: bun install
      - name: Run TypeScript Type Checking and ESLint
        run: bun run check
      - name: Build the Package
        run: bun run build:lib
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
